### ISSUE TITLE
FD_ISSET(tun_fd, &readset) always returns false

### ISSUE THREAD

**Issue by oliverhu** [lxdcn/simple-vpn-demo#10]
我把这个demo deploy到本地的一个linux机器一切正常，然后我尝试把这个跑在阿里云，udp打开相关端口，但是手机端连上去以后，server 输出只有：
```
Writing to tun 59 bytes ...
Writing to tun 60 bytes ...
Writing to tun 81 bytes ...
Writing to tun 57 bytes ...
Writing to tun 58 bytes ...
Writing to tun 58 bytes ...
Writing to tun 71 bytes ...
Writing to tun 71 bytes ...
Writing to tun 71 bytes ...

```
似乎tun_fd永远没被set，请问有什么debug的想法吗

**Comment by oliverhu** [comment]
google cloud也可以，只有aliyun不行

**Comment by oliverhu** [comment]
发现是因为那台机器已经部署了shadowsocks导致tunnel没法读取了，另外起了一个instance就好了

**Comment by YuejunChen** [comment]
> tunnel

老哥我也遇到这个情况，怎么排查呢

**Comment by FanLemon** [comment]
阿里云没有开启ip forward
国内的几家云厂商早就想到这点了，从一开始就给你屏蔽了。

**Comment by YuejunChen** [comment]
嗯嗯，腾讯云应该也一样，这个可以怎么解决吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "davlxd/simple-vpn-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 晚上9:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [davlxd/simple-vpn-demo] FD_ISSET(tun_fd, &amp;readset) always returns false (#10)





 
阿里云没有开启ip forward
 国内的几家云厂商早就想到这点了，从一开始就给你屏蔽了。

**Comment by FanLemon** [comment]
> 嗯嗯，腾讯云应该也一样，这个可以怎么解决吗？
> […](#)

无解吧。
这套代码依赖的关键点就是IP Forward，如果国产云无法“真实”的开启IP Forward.....你无论怎么折腾也没有用啊。

**Comment by YuejunChen** [comment]
我是mac电脑，用mac搞个docker镜像来跑这个程序，行得通吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "davlxd/simple-vpn-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 晚上9:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [davlxd/simple-vpn-demo] FD_ISSET(tun_fd, &amp;readset) always returns false (#10)





  
嗯嗯，腾讯云应该也一样，这个可以怎么解决吗？
 …
  
无解吧。
 这套代码依赖的关键点就是IP Forward，如果国产云无法“真实”的开启IP Forward.....你无论怎么折腾也没有用啊。

**Comment by FanLemon** [comment]
> 我是mac电脑，用mac搞个docker镜像来跑这个程序，行得通吗
> […](#)

mac上没必要套在docker里跑iptable啊.....直接用pf加ip forwarding
不过mac本体在墙内的话....也没意义....

**Comment by YuejunChen** [comment]
嗯嗯，是的，我并不是想实现VPN功能，而是想利用networkextension拦截数据包实现iOS的弱网模拟而已，这个您有什么好的建议吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "davlxd/simple-vpn-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 晚上9:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [davlxd/simple-vpn-demo] FD_ISSET(tun_fd, &amp;readset) always returns false (#10)





  
我是mac电脑，用mac搞个docker镜像来跑这个程序，行得通吗
 …
  
mac上没必要套在docker里跑iptable啊.....直接用pf加ip forwarding
 不过mac本体在墙内的话....也没意义....

**Comment by FanLemon** [comment]
> 嗯嗯，是的，我并不是想实现VPN功能，而是想利用networkextension拦截数据包实现iOS的弱网模拟而已，这个您有什么好的建议吗
> […](#)

https://stackoverflow.com/questions/12528986/using-the-network-link-conditioner-on-ios-devices

**Comment by YuejunChen** [comment]
谢谢，这个我清楚，目前是想做成这种的工具https://apps.apple.com/cn/app/id1541108317可以提供非开发人员使用，您觉得我可以把数据转发在ios本机上实现吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "davlxd/simple-vpn-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 晚上9:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [davlxd/simple-vpn-demo] FD_ISSET(tun_fd, &amp;readset) always returns false (#10)





  
嗯嗯，是的，我并不是想实现VPN功能，而是想利用networkextension拦截数据包实现iOS的弱网模拟而已，这个您有什么好的建议吗
 …
  
https://stackoverflow.com/questions/12528986/using-the-network-link-conditioner-on-ios-devices

**Comment by FanLemon** [comment]
> 谢谢，这个我清楚，目前是想做成这种的工具[https://apps.apple.com/cn/app/id1541108317可以提供非开发人员使用，您觉得我可以把数据转发在ios本机上实现吗](https://apps.apple.com/cn/app/id1541108317%E5%8F%AF%E4%BB%A5%E6%8F%90%E4%BE%9B%E9%9D%9E%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E4%BD%BF%E7%94%A8%EF%BC%8C%E6%82%A8%E8%A7%89%E5%BE%97%E6%88%91%E5%8F%AF%E4%BB%A5%E6%8A%8A%E6%95%B0%E6%8D%AE%E8%BD%AC%E5%8F%91%E5%9C%A8ios%E6%9C%AC%E6%9C%BA%E4%B8%8A%E5%AE%9E%E7%8E%B0%E5%90%97)
> […](#)

我初略推断，企鹅这个app是必须要连接服务器才能用的是吧？
如果是的，这app的原理跟此github的代码是一样的。iOS一旦开启ip layer的network-extension，就等于是用pf把ios全局流量转到新创建的utun上了，此后这些流量不送到外部服务器去做ip forwarding，就全废了。
省事的话，你本地找一个linux机器就搞定了啊。一定要docker应该也可以，google docker ip forward就有很多说法。

**Comment by YuejunChen** [comment]
他的服务器是192开头的，我理解是否是通过NE在隧道拦截流量然后通过socket转发到目的服务器，您觉得可以吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "davlxd/simple-vpn-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 晚上10:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [davlxd/simple-vpn-demo] FD_ISSET(tun_fd, &amp;readset) always returns false (#10)





  
谢谢，这个我清楚，目前是想做成这种的工具https://apps.apple.com/cn/app/id1541108317可以提供非开发人员使用，您觉得我可以把数据转发在ios本机上实现吗
 …
  
我初略推断，企鹅这个app是必须要连接服务器才能用的是吧？
 如果是的，这app的原理跟此github的代码是一样的。iOS一旦开启ip layer的network-extension，就等于是用pf把ios全局流量转到新创建的utun上了，此后这些流量不送到外部服务器去做ip forwarding，就全废了。
 省事的话，你本地找一个linux机器就搞定了啊。一定要docker应该也可以，google docker ip forward就有很多说法。

**Comment by FanLemon** [comment]
> 他的服务器是192开头的，我理解是否是通过NE在隧道拦截流量然后通过socket转发到目的服务器，您觉得可以吗
> […](#)

192是内网地址，意思是使用他这款app需要自己配置一个局域网内的server？
其实原理很简单，
1. iOS创建一个新的utun
2. iOS把网络流量nat到utun
3. iOS network-extension读取utun获得所有流量
4. 将所有流量通过socket送到服务器
5. 服务器做IP Forwarding
........

所谓模拟弱网，无外乎就是在第3和第4步骤之间人为的丢弃一些数据包。

**Comment by YuejunChen** [comment]
实在感谢您的指导，公司太难申请Linux机器了，才想着通过docker来实现，百忙中打扰您了，实在抱歉




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "davlxd/simple-vpn-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 上午7:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [davlxd/simple-vpn-demo] FD_ISSET(tun_fd, &amp;readset) always returns false (#10)





  
他的服务器是192开头的，我理解是否是通过NE在隧道拦截流量然后通过socket转发到目的服务器，您觉得可以吗
 …
  
192是内网地址，意思是使用他这款app需要自己配置一个局域网内的server？
 其实原理很简单，
  
iOS创建一个新的utun
 
iOS把网络流量nat到utun
 
iOS network-extension读取utun获得所有流量
 
将所有流量通过socket送到服务器
 
服务器做IP Forwarding
 ........
  
所谓模拟弱网，无外乎就是在第3和第4步骤之间人为的丢弃一些数据包。

**Comment by YuejunChen** [comment]
您好，再请教一个问题，如果程序是跑在虚拟机上的话是不是会被占有tun通道呢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "davlxd/simple-vpn-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 上午7:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [davlxd/simple-vpn-demo] FD_ISSET(tun_fd, &amp;readset) always returns false (#10)





  
他的服务器是192开头的，我理解是否是通过NE在隧道拦截流量然后通过socket转发到目的服务器，您觉得可以吗
 …
  
192是内网地址，意思是使用他这款app需要自己配置一个局域网内的server？
 其实原理很简单，
  
iOS创建一个新的utun
 
iOS把网络流量nat到utun
 
iOS network-extension读取utun获得所有流量
 
将所有流量通过socket送到服务器
 
服务器做IP Forwarding
 ........
  
所谓模拟弱网，无外乎就是在第3和第4步骤之间人为的丢弃一些数据包。

**Comment by FanLemon** [comment]
> 您好，再请教一个问题，如果程序是跑在虚拟机上的话是不是会被占有tun通道呢
> […](#)

读了几遍没太懂你具体的意思，我假设一下你的情况说说我的见解。
你有一台iPhone，和一台Mac。
iPhone上跑network-extension的代码，Mac上通过虚拟机装linux，跑服务器的代码。
以上，如果每个环节都确保正确运行，那就完全满足你的要求了。
唯一担心的只有虚拟机配置linux的ip forwarding可能要去google下文档。

关于tun相关，也不复杂。此github的代码原理就是分别在iPhone和linux上各建一个tun，然后对称的操作。具体可以参考
https://backreference.org/2010/03/26/tuntap-interface-tutorial/

**Comment by YuejunChen** [comment]
您好，想再咨询一个问题，如果想做成可以支持多个客户端连接的，服务端代码修改有什么好的思路吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "davlxd/simple-vpn-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [davlxd/simple-vpn-demo] FD_ISSET(tun_fd, &amp;readset) always returns false (#10)





  
您好，再请教一个问题，如果程序是跑在虚拟机上的话是不是会被占有tun通道呢
 …
  
读了几遍没太懂你具体的意思，我假设一下你的情况说说我的见解。
 你有一台iPhone，和一台Mac。
 iPhone上跑network-extension的代码，Mac上通过虚拟机装linux，跑服务器的代码。
 以上，如果每个环节都确保正确运行，那就完全满足你的要求了。
 唯一担心的只有虚拟机配置linux的ip forwarding可能要去google下文档。
 
关于tun相关，也不复杂。此github的代码原理就是分别在iPhone和linux上各建一个tun，然后对称的操作。具体可以参考
 https://backreference.org/2010/03/26/tuntap-interface-tutorial/

**Comment by FanLemon** [comment]
> 您好，想再咨询一个问题，如果想做成可以支持多个客户端连接的，服务端代码修改有什么好的思路吗
> […](#)

服务器端创建tun的地方改成一次性创建n个tun就行了，为每一个客户端分配一个tun。

**Comment by YuejunChen** [comment]
嗯嗯，好的，感谢😊



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 11, 2021 19:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [davlxd/simple-vpn-demo] FD_ISSET(tun_fd, &amp;readset) always returns false (#10)




  
您好，想再咨询一个问题，如果想做成可以支持多个客户端连接的，服务端代码修改有什么好的思路吗
 …
  
服务器端创建tun的地方改成一次性创建n个tun就行了，为每一个客户端分配一个tun。

**Comment by YuejunChen** [comment]
你好，创建多个tun和分配tun是通过多线程去处理对吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "davlxd/simple-vpn-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月11日(星期天) 晚上7:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [davlxd/simple-vpn-demo] FD_ISSET(tun_fd, &amp;readset) always returns false (#10)





  
您好，想再咨询一个问题，如果想做成可以支持多个客户端连接的，服务端代码修改有什么好的思路吗
 …
  
服务器端创建tun的地方改成一次性创建n个tun就行了，为每一个客户端分配一个tun。

**Comment by FanLemon** [comment]
> 你好，创建多个tun和分配tun是通过多线程去处理对吗
> […](#)

创建tun不用多线程，一个函数就能创建n个tun。
处理多client也不用多线程，一般fork或者select。

**Comment by YuejunChen** [comment]
你好，想再问下，udp_fd这个描述符可以复用吗？还是也要一次性新建n个？



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 12, 2021 20:16 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [davlxd/simple-vpn-demo] FD_ISSET(tun_fd, &amp;readset) always returns false (#10)




  
你好，创建多个tun和分配tun是通过多线程去处理对吗
 …
  
创建tun不用多线程，一个函数就能创建n个tun。
 处理多client也不用多线程，一般fork或者select。

**Comment by FanLemon** [comment]
> 你好，想再问下，udp_fd这个描述符可以复用吗？还是也要一次性新建n个？
> […](#)

UDP不用创建多个socket fd。server端创建一个UDP socket并且监听，就能收到任何发送到该server的udp数据。

**Comment by YuejunChen** [comment]
好的，所以只要创建多个tun并分配就可以实现多对一的模式了对吧？



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 14, 2021 21:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [davlxd/simple-vpn-demo] FD_ISSET(tun_fd, &amp;readset) always returns false (#10)




  
你好，想再问下，udp_fd这个描述符可以复用吗？还是也要一次性新建n个？
 …
  
UDP不用创建多个socket fd。server端创建一个UDP socket并且监听，就能收到任何发送到该server的udp数据。

**Comment by YuejunChen** [comment]
如何给每个客户端分配tun这个有什么好的建议嘛？



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 14, 2021 21:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [davlxd/simple-vpn-demo] FD_ISSET(tun_fd, &amp;readset) always returns false (#10)




  
你好，想再问下，udp_fd这个描述符可以复用吗？还是也要一次性新建n个？
 …
  
UDP不用创建多个socket fd。server端创建一个UDP socket并且监听，就能收到任何发送到该server的udp数据。

**Comment by FanLemon** [comment]
> 如何给每个客户端分配tun这个有什么好的建议嘛？
> […](#)

https://android.googlesource.com/kernel/msm/+/android-msm-bullhead-3.10-marshmallow-dr/Documentation/networking/tuntap.txt

**Comment by yingyangios** [comment]
> > 如何给每个客户端分配tun这个有什么好的建议嘛？
> > […](#)
> 
> https://android.googlesource.com/kernel/msm/+/android-msm-bullhead-3.10-marshmallow-dr/Documentation/networking/tuntap.txt

您好，我这边创建多个tun通道，但是发现只有第一个tun通道有数据可读，是因为iptable配置的问题吗

**Comment by FanLemon** [comment]
> > > 如何给每个客户端分配tun这个有什么好的建议嘛？
> > > […](#)
> > 
> > 
> > https://android.googlesource.com/kernel/msm/+/android-msm-bullhead-3.10-marshmallow-dr/Documentation/networking/tuntap.txt
> 
> 您好，我这边创建多个tun通道，但是发现只有第一个tun通道有数据可读，是因为iptable配置的问题吗

每个tun需要配置不同的ip地址，iptable确实也要检查看看是否规则适合你设定的ip地址。
