### ISSUE TITLE
never actually connects

### ISSUE THREAD

**Issue by aytunc** [lxdcn/simple-vpn-demo#4]
I'm having connection problem.
I set it up on DigitalOcean. But I never got a VPN connection.
What should I be server ip ? digitalocean server ip ? 

<img width="849" alt="ekran resmi 2017-04-30 21 19 22" src="https://cloud.githubusercontent.com/assets/10117849/25566843/b8f32438-2dea-11e7-9d61-263f8208b996.png">

![img_2055](https://cloud.githubusercontent.com/assets/10117849/25566941/0d791778-2dec-11e7-8c3f-4c7d780a8dae.PNG)

**Comment by davlxd** [comment]
I replied your email.
